package com.aviation.platform.common.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    INVALID_CREDENTIALS,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    RESOURCE_ALREADY_EXISTS,
    INVALID_STATE_TRANSITION,
    RESOURCE_LOCKED,
    ARTICLE_NOT_OWNED,
    QUIZ_ATTEMPT_LIMIT,
    LESSON_NOT_COMPLETED,
    INVALID_TOKEN,
    TOKEN_EXPIRED,
    INTERNAL_ERROR
}
