# One-off generator for V23 4-stage tower + pilot practice.
import json
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "src/main/resources/db/migration/V23__four_stage_tower_pilot.sql"


def esc(s: str) -> str:
    return s.replace("'", "''")


def q(s: str) -> str:
    return "'" + esc(s) + "'"


def cfg(d: dict) -> str:
    return q(json.dumps(d, ensure_ascii=False, separators=(",", ":"))) + "::jsonb"


def opts(correct: str, wrongs: list[str], rot: int) -> tuple[list[str], str]:
    items = [correct, *wrongs[:2]]
    r = rot % 3
    items = items[r:] + items[:r]
    return items, correct


def listen(stage, slug, title, desc, html, prompt, question, correct, wrongs, rot, extra=None):
    options, c = opts(correct, wrongs, rot)
    d = {"stage": stage, "promptText": prompt, "question": question, "options": options, "correctOption": c}
    if extra:
        d.update(extra)
    return ("LISTEN", slug, title, desc, html, d)


def speak(stage, slug, title, desc, html, prompt, expected, accepted, reply):
    return ("SPEAK", slug, title, desc, html, {
        "stage": stage,
        "promptText": prompt,
        "expectedPhrase": expected,
        "acceptedPhrases": accepted,
        "replyText": reply,
    })


def scene(stage, slug, title, desc, html, situation, correct, wrongs, rot, expected, reply):
    options, c = opts(correct, wrongs, rot)
    return ("SCENARIO", slug, title, desc, html, {
        "stage": stage,
        "situation": situation,
        "options": options,
        "correctOption": c,
        "expectedPhrase": expected,
        "replyText": reply,
    })


def content(stage, slug, title, desc, html):
    return ("CONTENT", slug, title, desc, html, {"stage": stage})


def live(stage, slug, title, desc, html):
    return ("LIVE_PRACTICE", slug, title, desc, html, {
        "stage": stage,
        "platform": "IVAO",
        "url": "https://www.ivao.aero",
        "instruction": "IVAO'da dinle veya sektor dene. En az bir cagri-cevap.",
    })


TOWER = []

TOWER.append(content(1, "twr1-intro", "Asama 1: Zemin",
    "Ground, taksi, kalkis ve inis izni.",
    "<p>Once yer: push, taxi, hold short, line up, take-off, land. Turkish, SunExpress, AJet (Anadolu), Pegasus karisik. Dogru sik her zaman A degil. Konus, dinle, sec.</p>"))

TOWER += [
    listen(1, "twr1-push-q", "Dinle: AJet push", "AJet = Anadolu.",
           "<p>AJet frekansta Anadolu diye okunur.</p>",
           "Istanbul Ground, AJet 221, stand 14, request push and start.",
           "Ucak ne istiyor?", "Push and start", ["Landing clearance", "Taxi to gate"], 2),
    speak(1, "twr1-push", "Konus: push onay", "Turkish 941.",
          "<p>Push and start approved.</p>",
          "Istanbul Ground, Turkish 941, stand 12, request push and start.",
          "Turkish 941 push and start approved",
          ["thy 941 push start approved", "push and start approved"],
          "Pushing, Turkish 941."),
    listen(1, "twr1-sxs-taxi", "Dinle: SunExpress taksi", "SXS.",
           "<p>SunExpress = sun express.</p>",
           "SunExpress 773, taxi to holding point runway 03 via Alpha, hold short.",
           "Nereye taksi?", "Alpha ile 03 holding, hold short", ["Direkt piste gir", "Stand 12'ye don"], 1),
    speak(1, "twr1-ajet-taxi", "Konus: AJet taksi", "Anadolu 221.",
          "<p>Taxi via Bravo, hold short 03.</p>",
          "Ground, AJet 221, request taxi.",
          "AJet 221 taxi via Bravo hold short runway 03",
          ["anadolu 221 taxi via bravo", "taxi via bravo hold short"],
          "Taxi via Bravo, AJet 221."),
    scene(1, "twr1-ready-taxi", "Senaryo: Pegasus taksi", "Apron.",
          "<p>Pegasus 12 ready for taxi.</p>",
          "Pegasus 12, stand 9, ready for taxi. Pist 03.",
          "Pegasus 12, taxi holding point 03 via Charlie, hold short",
          ["Pegasus 12, cleared for take-off", "Pegasus 12, go around"],
          0, "Pegasus 12 taxi via Charlie hold short", "Taxi via Charlie, Pegasus 12."),
    listen(1, "twr1-hold-q", "Dinle: hold short", "Cizgiyi gecme.",
           "<p>Hold short = o noktadan once dur.</p>",
           "Turkish 102J, hold short runway 03.",
           "Ucak ne yapacak?", "Pist cizgisinde bekleyecek", ["Kalkis izni aldi", "Pisti gecip taksi"], 2),
    speak(1, "twr1-hold", "Konus: hold short", "Turkish 102J.",
          "<p>Hold short runway 03.</p>",
          "Ground, Turkish 102J, approaching holding point 03.",
          "Turkish 102J hold short runway 03",
          ["hold short 03", "thy 102 juliet hold short"],
          "Holding short 03, Turkish 102J."),
    listen(1, "twr1-lineup-q", "Dinle: line up", "Kalkis izni degil.",
           "<p>Line up and wait: piste gir, bekle.</p>",
           "SunExpress 773, line up and wait runway 03.",
           "Kalkis izni var mi?", "Hayir, piste girip bekleyecek", ["Evet, kalkabilir", "Pistten gecis"], 1),
    speak(1, "twr1-lineup", "Konus: line up", "SunExpress.",
          "<p>Line up and wait.</p>",
          "SunExpress 773, ready for departure.",
          "SunExpress 773 line up and wait runway 03",
          ["sun express 773 line up and wait", "line up and wait 03"],
          "Lining up, SunExpress 773."),
    scene(1, "twr1-not-to", "Senaryo: henuz kalkis yok", "Holding.",
          "<p>Ready for departure, trafik finalde.</p>",
          "AJet 221 holding point 03, ready. Traffic on final.",
          "AJet 221, line up and wait runway 03",
          ["AJet 221, cleared for take-off", "AJet 221, cleared to land"],
          2, "AJet 221 line up and wait", "Lining up, AJet 221."),
    speak(1, "twr1-to", "Konus: take-off", "Pist musait.",
          "<p>Cleared for take-off.</p>",
          "AJet 221, lined up runway 03.",
          "AJet 221 runway 03 cleared for take-off",
          ["anadolu 221 cleared for takeoff", "cleared for take-off runway 03"],
          "Cleared for take-off, AJet 221."),
    listen(1, "twr1-vacate-q", "Dinle: vacated", "Pist bos.",
           "<p>Vacated = pistten cikti, ground'a gecir.</p>",
           "Pegasus 12, vacated runway 03, taxi via Bravo.",
           "Kule ne yapar?", "Ground frekansina gecirir", ["Yeni kalkis izni verir", "MAYDAY acar"], 0),
    speak(1, "twr1-ground", "Konus: contact ground", "121.7.",
          "<p>Contact ground.</p>",
          "Pegasus 12, vacated runway 03.",
          "Pegasus 12 contact ground 121.7",
          ["contact ground 121 decimal 7", "contact ground pegasus 12"],
          "Ground 121.7, Pegasus 12."),
    listen(1, "twr1-wind", "Dinle: ruzgar", "Inis bilgisi.",
           "<p>Wind 040 degrees 8 knots.</p>",
           "Turkish 1452, wind 040 degrees 8 knots, runway 05, cleared to land.",
           "Ruzgar nedir?", "040 derece, 8 knot", ["220 derece, 18 knot", "Pist kapali"], 2),
    speak(1, "twr1-land", "Konus: cleared to land", "Turkish 1452.",
          "<p>Cleared to land 05.</p>",
          "Turkish 1452, final runway 05.",
          "Turkish 1452 runway 05 cleared to land",
          ["cleared to land runway 05", "thy 1452 cleared to land"],
          "Cleared to land, Turkish 1452."),
    scene(1, "twr1-land-rb", "Senaryo: inis izni", "Pist musait.",
          "<p>AJet 45C final 05, ruzgar uygun.</p>",
          "AJet 45C final runway 05, wind 040/8, runway clear.",
          "AJet 45C, runway 05, cleared to land, wind 040 degrees 8 knots",
          ["AJet 45C, go around", "AJet 45C, hold short 05"],
          1, "AJet 45C cleared to land runway 05", "Cleared to land, AJet 45C."),
    listen(1, "twr1-charlie-q", "Dinle: Charlie", "Taxiway C.",
           "<p>Charlie = C. Charli de ayni.</p>",
           "Turkish 102J, taxi via Charlie, hold short runway 03.",
           "Hangi taxiway?", "Charlie", ["Alpha", "Bravo"], 0),
    speak(1, "twr1-charlie", "Konus: via Charlie", "Alfabe.",
          "<p>Taxi via Charlie.</p>",
          "Ground, Turkish 102J, request taxi.",
          "taxi via Charlie",
          ["taxi via charli", "charlie", "charli"],
          "Taxi via Charlie, Turkish 102J."),
    speak(1, "twr1-abc", "Konus: Alpha Bravo Charlie", "A B C.",
          "<p>Alfa, Bravo, Charli. Yuzde 50 yeter.</p>",
          "Say taxiway letters A B C.",
          "Alpha Bravo Charlie",
          ["alfa bravo charli", "alpha bravo"],
          "Alpha Bravo Charlie."),
    listen(1, "twr1-anadolu", "Dinle: AJet okunus", "Anadolu.",
           "<p>AJet cagri isareti sozlu: Anadolu.</p>",
           "Anadolu 221, taxi via Bravo.",
           "Bu ucak hangi sirket?", "AJet (Anadolu)", ["SunExpress", "Pegasus"], 1),
    scene(1, "twr1-first-call", "Senaryo: ilk cagri", "Kim once?",
          "<p>Standart: birim, cagri isareti, konum, talep.</p>",
          "Yeni ucak ground'u arayacak. Dogru sira?",
          "Istanbul Ground, SunExpress 773, stand 8, request push and start",
          ["Push and start, Ground, SunExpress", "SunExpress 773, go around"],
          2, "Istanbul Ground SunExpress 773 request push", "Roger, SunExpress 773."),
    speak(1, "twr1-tower-freq", "Konus: contact tower", "118.1.",
          "<p>Ground bitti, kuleye gecir.</p>",
          "Turkish 941, ready for departure.",
          "Turkish 941 contact tower 118.1",
          ["contact tower 118 decimal 1", "contact tower thy 941"],
          "Tower 118.1, Turkish 941."),
    listen(1, "twr1-ident-q", "Dinle: ident", "Radar.",
           "<p>Squawk ident = transponder ident.</p>",
           "SunExpress 58T, squawk ident.",
           "Ucak ne yapacak?", "Ident basacak", ["Mayday acacak", "Pisti terk edecek"], 0),
    speak(1, "twr1-ident", "Konus: ident", "Turkish 941.",
          "<p>Ident.</p>",
          "Turkish 941, squawk ident.",
          "Ident Turkish 941",
          ["squawk ident turkish 941", "ident thy 941"],
          "Ident, Turkish 941."),
]

TOWER.append(content(2, "twr2-intro", "Asama 2: Havada trafik",
    "Yaklasma, iki ucaga ayni anda, sira.",
    "<p>Simdi hava: number 2, extend downwind, go around, give way. Iki cagri isareti ayni anda. SunExpress finaldeyken AJet base'te olabilir.</p>"))

TOWER += [
    listen(2, "twr2-num2-q", "Dinle: number 2", "Sira.",
           "<p>Number 2 = onunde bir ucak var.</p>",
           "AJet 221, number 2, continue approach.",
           "Ne anlama gelir?", "Ikinci sirada, yaklasmaya devam", ["Kalkis izni", "Pistte bekle"], 2),
    speak(2, "twr2-num2", "Konus: number 2", "AJet.",
          "<p>Number 2, continue approach.</p>",
          "AJet 221, base runway 05.",
          "AJet 221 number 2 continue approach",
          ["anadolu 221 number 2", "number 2 continue approach"],
          "Number 2, AJet 221."),
    scene(2, "twr2-two", "Senaryo: iki ucak", "Final + downwind.",
          "<p>SunExpress 773 finalde, AJet 221 downwind. Pist tek.</p>",
          "SunExpress 773 on final, AJet 221 downwind 05. Pist musait degil ikinciye.",
          "SunExpress 773, cleared to land. AJet 221, extend downwind",
          ["AJet 221, cleared to land. SunExpress 773, go around", "Ikisine birden take-off"],
          1, "SunExpress 773 cleared to land AJet 221 extend downwind",
          "Cleared to land, SunExpress. Extending, AJet 221."),
    speak(2, "twr2-extend", "Konus: extend downwind", "Aralik.",
          "<p>Extend downwind.</p>",
          "Turkish 1452, downwind runway 05.",
          "Turkish 1452 extend downwind",
          ["extend downwind thy 1452", "extend downwind"],
          "Extending downwind, Turkish 1452."),
    listen(2, "twr2-ga-q", "Dinle: go around trafik", "Pist mesgul.",
           "<p>Pistte hala biri varken finaldekiye go around.</p>",
           "Pegasus 88, go around, traffic on the runway.",
           "Neden pas geciyor?", "Pistte trafik var", ["Yakit bitti", "Ruzgar sifir"], 0),
    speak(2, "twr2-ga", "Konus: go around", "SunExpress final.",
          "<p>Go around.</p>",
          "SunExpress 773, final runway 05. Runway occupied.",
          "SunExpress 773 go around",
          ["sun express 773 go around", "go around"],
          "Going around, SunExpress 773."),
    scene(2, "twr2-giveway", "Senaryo: give way", "Apron cikis.",
          "<p>AJet takside, Pegasus cikiyor.</p>",
          "AJet 221 taxi Bravo. Pegasus 12 pushing from stand 9 onto Bravo.",
          "AJet 221, give way to Pegasus 12 from the right",
          ["AJet 221, cleared for take-off", "Pegasus 12, go around"],
          2, "AJet 221 give way Pegasus 12", "Giving way, AJet 221."),
    speak(2, "twr2-orbit", "Konus: orbit left", "Iki dakika.",
          "<p>Orbit left.</p>",
          "Turkish 941, need two minutes, traffic on the runway.",
          "Turkish 941 orbit left",
          ["orbit left thy 941", "orbit left"],
          "Orbiting left, Turkish 941."),
    listen(2, "twr2-final-q", "Dinle: report final", "Pozisyon.",
           "<p>Report final = finalde bildir.</p>",
           "AJet 45C, number 2, report final.",
           "Ucak ne zaman konusur?", "Finalde", ["Kalkista", "Apronda"], 1),
    speak(2, "twr2-continue", "Konus: continue approach", "Henuz inis izni yok.",
          "<p>Continue approach.</p>",
          "Pegasus 12, long final 05.",
          "Pegasus 12 continue approach",
          ["continue approach pegasus 12", "continue approach"],
          "Continuing, Pegasus 12."),
    scene(2, "twr2-seq", "Senaryo: sira 1-2", "Uc ucak.",
          "<p>Biri iniste, biri base, biri downwind.</p>",
          "Turkish 102J short final, SunExpress 773 base, AJet 221 downwind.",
          "Turkish 102J, cleared to land. SunExpress 773, number 2. AJet 221, extend downwind",
          ["Hepsi cleared to land", "Hepsi go around"],
          0, "Turkish 102J cleared to land SunExpress number 2",
          "Roger."),
    speak(2, "twr2-traffic", "Konus: traffic info", "Bilgi.",
          "<p>Traffic, Airbus on final.</p>",
          "AJet 221, looking for traffic.",
          "AJet 221 traffic Airbus on final",
          ["anadolu 221 traffic on final", "traffic airbus on final"],
          "Traffic in sight, AJet 221."),
    listen(2, "twr2-behind", "Dinle: behind landing", "Wake.",
           "<p>Behind landing traffic.</p>",
           "SunExpress 773, behind landing A320, cleared for take-off.",
           "Ne bekliyor?", "Inen A320'nin ardindan kalkis", ["Go around", "Hold short sadece"], 2),
    speak(2, "twr2-expedite", "Konus: expedite", "Hizlan.",
          "<p>Expedite vacating.</p>",
          "Turkish 1452, landed, still on 05. Next on short final.",
          "Turkish 1452 expedite vacating",
          ["expedite vacating thy 1452", "expedite vacating"],
          "Expediting, Turkish 1452."),
    scene(2, "twr2-cross", "Senaryo: cross runway", "Taksi + final.",
          "<p>Pegasus pistten gecmek istiyor, finalde SunExpress.</p>",
          "Pegasus 12 request cross 03. SunExpress 773 4 miles final.",
          "Pegasus 12, hold short runway 03, traffic on final",
          ["Pegasus 12, cross 03, SunExpress go around", "Ikisi de cleared to land"],
          1, "Pegasus 12 hold short runway 03", "Holding short, Pegasus 12."),
    speak(2, "twr2-cross-ok", "Konus: cross", "Final bos.",
          "<p>Cross runway 03.</p>",
          "Pegasus 12, request cross runway 03. Final clear.",
          "Pegasus 12 cross runway 03",
          ["cross runway 03 pegasus 12", "cross 03"],
          "Crossing 03, Pegasus 12."),
    listen(2, "twr2-delay", "Dinle: delay", "Yogun.",
           "<p>Delay 5 minutes due traffic.</p>",
           "AJet 221, delay 5 minutes due inbound traffic.",
           "Ne olacak?", "5 dakika gecikme", ["Hemen inis izni", "Mayday"], 0),
    speak(2, "twr2-num1", "Konus: number 1", "Sira geldi.",
          "<p>Number 1, report final.</p>",
          "SunExpress 773, on base.",
          "SunExpress 773 number 1 report final",
          ["sun express number 1 report final", "number 1 report final"],
          "Number 1, SunExpress 773."),
    scene(2, "twr2-same-time", "Senaryo: ayni anda iki cagri", "Frekans.",
          "<p>Ikisi birden konusuyor. Once acil olmayan, once finaldekine cevap.</p>",
          "Ayni anda: AJet 221 'request taxi'. SunExpress 773 'final 05'.",
          "Once SunExpress 773, runway 05 cleared to land. Sonra AJet 221, standby",
          ["Once AJet taksi, SunExpress beklesin", "Ikisine go around"],
          2, "SunExpress 773 cleared to land AJet 221 standby",
          "Cleared to land, SunExpress. Standby, AJet."),
    speak(2, "twr2-standby", "Konus: standby", "Dolu frekans.",
          "<p>Standby.</p>",
          "AJet 221, request taxi while you talk to SunExpress on final.",
          "AJet 221 standby",
          ["anadolu 221 standby", "standby"],
          "Standing by, AJet 221."),
    listen(2, "twr2-unable", "Dinle: unable", "Yapamiyor.",
           "<p>Unable due traffic.</p>",
           "Turkish 941, unable immediate take-off due inbound on 4 miles.",
           "Kule neden bekletiyor?", "Gelen trafik", ["Hava kapali", "Yakit"], 1),
    speak(2, "twr2-after", "Konus: after the landing", "Sirali kalkis.",
          "<p>After the landing A320, line up.</p>",
          "Pegasus 12, ready, A320 on short final.",
          "Pegasus 12 after the landing line up and wait",
          ["after the landing line up", "line up after landing"],
          "After the landing, Pegasus 12."),
    scene(2, "twr2-wake", "Senaryo: wake", "Agir ucak.",
          "<p>Turkish 777 iniste, arkasindan AJet.</p>",
          "Turkish 941 B777 short final. AJet 221 3 miles behind.",
          "AJet 221, caution wake turbulence, number 2",
          ["AJet 221, cleared to land immediately", "AJet 221, take-off"],
          0, "AJet 221 caution wake turbulence number 2", "Number 2, AJet 221."),
    speak(2, "twr2-low", "Konus: low approach", "Geciş.",
          "<p>Low approach approved, go around at 500 feet.</p>",
          "SunExpress 773, request low approach 05.",
          "SunExpress 773 low approach approved",
          ["low approach approved", "sun express low approach"],
          "Low approach, SunExpress 773."),
]

TOWER.append(content(3, "twr3-intro", "Asama 3: PAN ve yogun trafik",
    "PAN PAN, gecikme, yogun saat.",
    "<p>PAN PAN hayati tehlike degil ama acil. Yogun trafikte kule kisa konusur, sira verir, delay soyler, unable der. MAYDAY henuz degil.</p>"))

TOWER += [
    listen(3, "twr3-pan-q", "Dinle: PAN PAN", "Aciliyet.",
           "<p>PAN PAN uc kez. Hayat yok, acil var.</p>",
           "PAN PAN PAN, AJet 221, medical situation on board.",
           "Bu cagri ne?", "Acil, hayati tehlike yok", ["Rutin taksi", "Ucak dusuyor"], 1),
    speak(3, "twr3-pan-ack", "Konus: PAN roger", "AJet.",
          "<p>Roger PAN PAN, say intentions.</p>",
          "PAN PAN PAN, AJet 221, medical on board, request priority landing.",
          "AJet 221 roger PAN PAN runway 05",
          ["anadolu 221 roger pan pan", "roger pan pan"],
          "Roger PAN, AJet 221."),
    scene(3, "twr3-pan-priority", "Senaryo: PAN oncelik", "Final dolu.",
          "<p>SunExpress finalde, AJet PAN medical.</p>",
          "SunExpress 773 6 miles final. AJet 221 PAN PAN medical, request priority.",
          "AJet 221, runway 05, cleared to land. SunExpress 773, extend downwind",
          ["SunExpress cleared to land, AJet hold", "Ikisi go around"],
          2, "AJet 221 cleared to land SunExpress extend downwind",
          "Cleared to land, AJet. Extending, SunExpress."),
    speak(3, "twr3-pan-fuel", "Konus: PAN fuel", "Yakit az.",
          "<p>PAN PAN, minimum fuel.</p>",
          "PAN PAN PAN, Turkish 1452, minimum fuel, request immediate landing.",
          "Turkish 1452 roger PAN PAN cleared to land runway 05",
          ["roger pan pan cleared to land", "thy 1452 cleared to land"],
          "Cleared to land, Turkish 1452."),
    listen(3, "twr3-bird", "Dinle: bird strike PAN", "Kus.",
           "<p>Bird strike, engine check, PAN.</p>",
           "PAN PAN, Pegasus 12, bird strike, request return.",
           "Kule ne bekler?", "Donus ve oncelikli inis", ["Normal taksi", "Squawk 2000"], 0),
    speak(3, "twr3-return", "Konus: come back", "Donus.",
          "<p>Turn back, runway 03, cleared to land.</p>",
          "PAN PAN, Pegasus 12, bird strike, request return.",
          "Pegasus 12 turn back runway 03 cleared to land",
          ["turn back cleared to land", "pegasus 12 cleared to land"],
          "Turning back, Pegasus 12."),
    scene(3, "twr3-busy", "Senaryo: yogun saat", "Dort ucak.",
          "<p>Iki final, biri taxi, biri PAN fuel.</p>",
          "Turkish 941 PAN minimum fuel. SunExpress 773 final. AJet 221 taxi. Pegasus 12 downwind.",
          "Turkish 941, number 1, cleared to land. Digerleri delay / extend",
          ["Once AJet taksi ver, PAN beklesin", "Herkese take-off"],
          1, "Turkish 941 number 1 cleared to land", "Cleared to land, Turkish 941."),
    speak(3, "twr3-delay", "Konus: delay due", "Yogun.",
          "<p>Delay 10 minutes due traffic.</p>",
          "AJet 221, request taxi, frequency busy.",
          "AJet 221 delay 10 minutes due traffic",
          ["delay 10 minutes", "anadolu 221 delay"],
          "Delay 10 minutes, AJet 221."),
    listen(3, "twr3-unable-q", "Dinle: unable", "Simdilik yok.",
           "<p>Unable take-off, inbound 3 miles.</p>",
           "SunExpress 773, unable immediate departure, inbound 3 miles.",
           "Ne yapamaz?", "Hemen kalkis", ["Inis", "Taksi"], 2),
    speak(3, "twr3-unable", "Konus: unable", "Kalkis yok.",
          "<p>Unable, hold position.</p>",
          "SunExpress 773, ready, inbound on 3 miles.",
          "SunExpress 773 unable hold position",
          ["unable hold position", "sun express hold position"],
          "Holding, SunExpress 773."),
    scene(3, "twr3-radio", "Senaryo: zayif radyo", "Say again.",
          "<p>Pegasus kirik cagri.</p>",
          "Pegasus 12, broken read-back, you heard only 'runway'.",
          "Pegasus 12, say again",
          ["Pegasus 12, cleared for take-off anyway", "Ignore"],
          0, "Pegasus 12 say again", "Say again, Pegasus 12."),
    speak(3, "twr3-sayagain", "Konus: say again", "Anlasilmadi.",
          "<p>Say again.</p>",
          "AJet 221, (garbled) request something.",
          "AJet 221 say again",
          ["say again anadolu 221", "say again"],
          "AJet 221, request taxi."),
    listen(3, "twr3-7600", "Dinle: 7600", "Radyo arizasi.",
           "<p>Squawk 7600 = NORDO. Henuz MAYDAY degil.</p>",
           "Turkish 102J squawking 7600, no radio.",
           "Ne anlama gelir?", "Radyo arizasi", ["Kacirma", "Yakit bitti"], 1),
    speak(3, "twr3-light", "Konus: light signals", "NORDO.",
          "<p>If you read, ident. Cleared to land, green light.</p>",
          "Turkish 102J, 7600, on final, no radio.",
          "Turkish 102J cleared to land ident if you read",
          ["cleared to land ident", "thy 102 juliet cleared to land"],
          "(ident flash)"),
    scene(3, "twr3-medical", "Senaryo: ambulans", "PAN medical.",
          "<p>Inis sonrasi saglik ekibi.</p>",
          "AJet 221 PAN medical landed 05, request ambulance on taxiway Bravo.",
          "AJet 221, taxi Bravo, ambulance is rolling",
          ["AJet 221, go around", "Ignore medical"],
          2, "AJet 221 taxi Bravo ambulance rolling", "Taxi Bravo, AJet 221."),
    speak(3, "twr3-ambulance", "Konus: ambulance", "Ekip.",
          "<p>Ambulance rolling, taxi Bravo.</p>",
          "AJet 221, vacated, medical on board.",
          "AJet 221 taxi Bravo ambulance rolling",
          ["taxi bravo ambulance", "anadolu 221 ambulance"],
          "Taxi Bravo, AJet 221."),
    listen(3, "twr3-hold", "Dinle: hold for delay", "Bekleme.",
           "<p>Hold at Golf, delay 8 minutes.</p>",
           "Pegasus 12, hold at Golf, delay 8 minutes due inbound.",
           "Nerede bekler?", "Golf", ["Pist ortasi", "Apron kapali"], 0),
    speak(3, "twr3-holdgolf", "Konus: hold Golf", "Yogun.",
          "<p>Hold at Golf.</p>",
          "Pegasus 12, request taxi, inbound stream.",
          "Pegasus 12 hold at Golf",
          ["hold at golf", "pegasus 12 hold golf"],
          "Holding Golf, Pegasus 12."),
    scene(3, "twr3-expedite-all", "Senaryo: expedite hepsi", "Zincir.",
          "<p>PAN iniste, arkadakiler hizlansin.</p>",
          "Turkish 1452 PAN fuel on 2 miles. SunExpress 773 on Bravo still.",
          "SunExpress 773, expedite, vacate Bravo. Turkish 1452, continue, cleared to land",
          ["SunExpress cleared to land, PAN hold", "Ikisi orbit"],
          1, "SunExpress 773 expedite Turkish 1452 cleared to land",
          "Expediting. Cleared to land."),
    speak(3, "twr3-caution", "Konus: caution", "Islak pist.",
          "<p>Caution, wet runway.</p>",
          "AJet 221, final 05, rain.",
          "AJet 221 caution wet runway",
          ["caution wet runway", "anadolu 221 wet runway"],
          "Caution wet runway, AJet 221."),
    listen(3, "twr3-priority", "Dinle: priority", "PAN sirasi.",
           "<p>You are number 1, priority.</p>",
           "Turkish 1452, you are number 1, priority landing.",
           "Sira?", "Birinci, oncelik", ["Sonuncu", "Taksi"], 2),
    speak(3, "twr3-num1-pan", "Konus: number 1 priority", "PAN.",
          "<p>Number 1, priority, cleared to land.</p>",
          "PAN PAN, SunExpress 773, medical, 8 miles.",
          "SunExpress 773 number 1 priority cleared to land",
          ["number 1 priority cleared to land", "sun express cleared to land"],
          "Number 1, SunExpress 773."),
    scene(3, "twr3-break", "Senaryo: break break", "Cakisan cagri.",
          "<p>Iki ucak ust uste. Break break.</p>",
          "AJet and Pegasus talking over each other. PAN from Turkish starting.",
          "Break break, Turkish 941, go ahead",
          ["Ignore PAN, continue taxi chatter", "All aircraft go around"],
          0, "break break Turkish 941 go ahead", "Turkish 941, PAN PAN..."),
    speak(3, "twr3-break", "Konus: break break", "Frekans.",
          "<p>Break break, this is Tower.</p>",
          "Two aircraft overlapping, you need the PAN.",
          "break break Tower",
          ["break break", "break break this is tower"],
          "Tower, go ahead."),
]

TOWER.append(content(4, "twr4-intro", "Asama 4: MAYDAY",
    "Motor, basinc, hidrolik. Yolcu, yakit, kargo. Itfaiye.",
    "<p>MAYDAY uc kez: hayati tehlike. Kule: pist, acil ekip, souls on board, fuel remaining, dangerous goods. Gercek kule gibi sor.</p>"))

TOWER += [
    listen(4, "twr4-mayday-q", "Dinle: MAYDAY", "Hayat.",
           "<p>MAYDAY MAYDAY MAYDAY.</p>",
           "MAYDAY MAYDAY MAYDAY, AJet 221, engine failure, request the field.",
           "Ne anlama gelir?", "Hayati tehlike, oncelik", ["Sadece gecikme", "Rutin"], 1),
    speak(4, "twr4-mayday-ack", "Konus: roger MAYDAY", "Pist senin.",
          "<p>Roger MAYDAY, runway 03 is yours.</p>",
          "MAYDAY MAYDAY MAYDAY, AJet 221, engine failure.",
          "AJet 221 roger MAYDAY runway 03 is yours",
          ["roger mayday runway 03", "anadolu 221 roger mayday"],
          "Runway 03, AJet 221."),
    scene(4, "twr4-engine", "Senaryo: motor kaybi", "Final dolu.",
          "<p>MAYDAY engine, oteki finalde.</p>",
          "AJet 221 MAYDAY engine. SunExpress 773 5 miles final.",
          "AJet 221, runway 03 yours. SunExpress 773, go around",
          ["SunExpress land first, MAYDAY hold", "Ikisi line up"],
          2, "AJet 221 runway 03 yours SunExpress go around",
          "Runway 03, AJet. Going around, SunExpress."),
    speak(4, "twr4-souls", "Konus: souls on board", "Kule sorar.",
          "<p>Souls on board, fuel remaining, dangerous goods?</p>",
          "AJet 221, MAYDAY, engine, descending.",
          "AJet 221 souls on board fuel remaining dangerous goods",
          ["souls on board fuel remaining", "anadolu 221 souls on board"],
          "148 souls, fuel 2 hours, no dangerous goods."),
    listen(4, "twr4-souls-q", "Dinle: souls", "Yolcu sayisi.",
           "<p>Souls on board = canli sayisi.</p>",
           "Tower: AJet 221, souls on board? Pilot: 148 souls.",
           "Kule ne ogrenir?", "Yolcu+ekip sayisi 148", ["Yakit 148 ton", "Pist 148"], 0),
    speak(4, "twr4-fuel", "Konus: fuel remaining", "Yakit.",
          "<p>Fuel remaining?</p>",
          "Turkish 941, MAYDAY, hydraulic.",
          "Turkish 941 fuel remaining",
          ["fuel remaining thy 941", "fuel remaining"],
          "Fuel 40 minutes, Turkish 941."),
    scene(4, "twr4-hydro", "Senaryo: hidrolik", "Dusuk basinc.",
          "<p>Hydraulic, gear may not down.</p>",
          "SunExpress 773 MAYDAY hydraulic, possible no gear. Request long runway, foam.",
          "SunExpress 773, runway 03, foam standing by, souls and fuel please",
          ["SunExpress, taxi via Alpha", "Ignore foam"],
          1, "SunExpress 773 runway 03 foam standing by", "Runway 03, SunExpress 773."),
    speak(4, "twr4-foam", "Konus: foam standing by", "Itfaiye.",
          "<p>Foam standing by.</p>",
          "SunExpress 773, MAYDAY hydraulic, request foam.",
          "SunExpress 773 foam standing by runway 03",
          ["foam standing by", "sun express foam runway 03"],
          "Foam, SunExpress 773."),
    listen(4, "twr4-cargo", "Dinle: dangerous goods", "Kargo.",
           "<p>Dangerous goods / cargo.</p>",
           "Tower asks Pegasus 12 dangerous goods. Pilot: none.",
           "Kule neden sorar?", "Acil ekip neyle mucadele edecek", ["Rutin check-in", "Squawk"], 2),
    speak(4, "twr4-goods", "Konus: dangerous goods", "Kargo sor.",
          "<p>Any dangerous goods?</p>",
          "Pegasus 12, MAYDAY, smoke in hold.",
          "Pegasus 12 any dangerous goods",
          ["dangerous goods", "any dangerous goods pegasus 12"],
          "No dangerous goods, Pegasus 12."),
    scene(4, "twr4-press", "Senaryo: basinc kaybi", "Decompression.",
          "<p>Cabin pressure, emergency descent.</p>",
          "Turkish 1452 MAYDAY, cabin decompression, emergency descent, request 03.",
          "Turkish 1452, roger MAYDAY, descend, runway 03 is yours, souls and fuel",
          ["Turkish 1452, continue cruise", "Hold short"],
          0, "Turkish 1452 roger MAYDAY runway 03 is yours",
          "Descending, Turkish 1452."),
    speak(4, "twr4-descend", "Konus: emergency descent", "Alcal.",
          "<p>Roger MAYDAY, descend, runway yours.</p>",
          "MAYDAY, Turkish 1452, decompression.",
          "Turkish 1452 roger MAYDAY descend runway 03 is yours",
          ["roger mayday descend runway 03", "thy 1452 runway 03 is yours"],
          "Descending, Turkish 1452."),
    listen(4, "twr4-7700", "Dinle: 7700", "Transponder.",
           "<p>Squawk 7700 genel acil.</p>",
           "AJet 221, squawk 7700.",
           "Kod ne?", "Genel acil durum", ["Radyo arizasi 7600", "Korsanlik 7500"], 1),
    speak(4, "twr4-squawk", "Konus: squawk 7700", "Kod.",
          "<p>Squawk 7700.</p>",
          "AJet 221, MAYDAY, engine.",
          "AJet 221 squawk 7700",
          ["squawk 7700", "anadolu 221 squawk 7700"],
          "7700, AJet 221."),
    scene(4, "twr4-services", "Senaryo: acil ekipler", "Kule cagirir.",
          "<p>Itfaiye, ambulans, pist 03.</p>",
          "MAYDAY AJet 221 engine, 8 miles. You call airport emergency.",
          "Emergency services, AJet 221 engine failure, runway 03, 8 miles, souls 148, fuel 2 hours",
          ["No need to call anyone", "Tell him to taxi Golf"],
          2, "emergency services runway 03 AJet 221",
          "Services rolling."),
    speak(4, "twr4-services", "Konus: emergency services", "Cagri.",
          "<p>Airport emergency, engine failure, runway 03.</p>",
          "You are TWR. MAYDAY AJet 221, 8 miles, 148 souls.",
          "emergency services AJet 221 engine failure runway 03",
          ["emergency services runway 03", "emergency services"],
          "Services rolling."),
    listen(4, "twr4-evac", "Dinle: evacuate", "Tahliye.",
           "<p>Evacuate on the runway if needed.</p>",
           "AJet 221, if unable to taxi, evacuate on the runway, services with you.",
           "Pilot ne yapabilir?", "Pistte tahliye", ["Tekrar kalkis", "IVAO kapat"], 0),
    speak(4, "twr4-evac", "Konus: evacuate", "Pistte.",
          "<p>Evacuate on the runway, services with you.</p>",
          "AJet 221, stopped on 03, smoke.",
          "AJet 221 evacuate on the runway services with you",
          ["evacuate on the runway", "anadolu 221 evacuate"],
          "Evacuating, AJet 221."),
    scene(4, "twr4-crash", "Senaryo: dusmek uzere", "Son mil.",
          "<p>Kontrol zayif, pist senin, herkes cekilsin.</p>",
          "Turkish 941 MAYDAY, flight controls, crash possible, 2 miles.",
          "All traffic, stop. Turkish 941, runway 03 yours, services rolling, souls and fuel",
          ["Turkish 941, number 3, continue", "Cleared for take-off next"],
          1, "Turkish 941 runway 03 is yours services rolling",
          "Runway in sight, Turkish 941."),
    speak(4, "twr4-yours", "Konus: runway is yours", "Her sey durur.",
          "<p>Runway 03 is yours, services rolling.</p>",
          "MAYDAY MAYDAY MAYDAY, Turkish 941, going down.",
          "Turkish 941 runway 03 is yours services rolling",
          ["runway 03 is yours", "thy 941 runway is yours"],
          "Runway 03, Turkish 941."),
    listen(4, "twr4-gear", "Dinle: gear", "Hidrolik.",
           "<p>Confirm gear down?</p>",
           "SunExpress 773, confirm gear down.",
           "Kule neyi teyit eder?", "Inis takimlari", ["Yolcu yemegi", " squawk 2000"], 2),
    speak(4, "twr4-gear", "Konus: confirm gear", "Takim.",
          "<p>Confirm gear down.</p>",
          "SunExpress 773, MAYDAY hydraulic, 4 miles.",
          "SunExpress 773 confirm gear down",
          ["confirm gear down", "sun express gear down"],
          "Gear down, SunExpress 773."),
    scene(4, "twr4-full", "Senaryo: tam kule listesi", "Hepsini sor.",
          "<p>MAYDAY sonra: pist, 7700, souls, fuel, cargo, ekipler.</p>",
          "Pegasus 12 MAYDAY smoke. You have 20 seconds on frequency.",
          "Pegasus 12, roger MAYDAY, runway 03 yours, squawk 7700, souls, fuel, dangerous goods? Services rolling",
          ["Pegasus 12, contact ground, have a nice day", "Standby indefinitely"],
          0, "Pegasus 12 roger MAYDAY runway 03 souls fuel",
          "148 souls, 30 minutes, no DG."),
    speak(4, "twr4-full", "Konus: tam MAYDAY paketi", "Hepsini soyle.",
          "<p>Roger MAYDAY, runway yours, souls, fuel, goods.</p>",
          "MAYDAY MAYDAY MAYDAY, Pegasus 12, smoke in cockpit.",
          "Pegasus 12 roger MAYDAY runway 03 is yours souls on board fuel remaining",
          ["roger mayday runway 03 souls fuel", "pegasus 12 runway is yours"],
          "Runway 03, 90 souls, fuel 25 minutes, no dangerous goods."),
    live(4, "twr4-ivao", "Canli: IVAO sektor", "Hatti bitirdin.",
         "<p>Giris yapanlar: puan dolunca sektor acmayi deneyebilirsin. Once observer dinle, sonra ADC.</p>"),
]


def plt_listen(stage, slug, title, desc, html, prompt, question, correct, wrongs, rot):
    return listen(stage, slug, title, desc, html, prompt, question, correct, wrongs, rot)


PILOT = []
PILOT.append(content(1, "plt1-intro", "Asama 1: Yer ve izinler",
    "Ground, taksi, line up, kalkis, inis read-back.",
    "<p>Pilot: kuleyi ara, talimati tekrarla. AJet = Anadolu. Yuzde 50 yakin yeter.</p>"))

PILOT += [
    plt_listen(1, "plt1-who", "Dinle: ilk cagri", "Sira.",
               "<p>Birim, cagri, konum, talep.</p>",
               "Ankara Tower, AJet 221, stand 14, request pushback and start-up",
               "Pilot ne istiyor?", "Pushback and start-up", ["Landing", "Go around"], 2),
    speak(1, "plt1-push", "Konus: push talebi", "Anadolu 221.",
          "<p>Ankara Tower, AJet 221, request push and start.</p>",
          "Sen AJet 221, stand 14.",
          "Ankara Tower AJet 221 request push and start",
          ["anadolu 221 request push", "tower ajet 221 push and start"],
          "AJet 221, push and start approved."),
    speak(1, "plt1-taxi", "Konus: taksi talebi", "SunExpress.",
          "<p>Ground, SunExpress 773, request taxi.</p>",
          "You are SunExpress 773, stand 8.",
          "Ground SunExpress 773 request taxi",
          ["sun express 773 request taxi", "ground request taxi"],
          "SunExpress 773, taxi via Alpha, hold short 03."),
    plt_listen(1, "plt1-rb-taxi", "Dinle: taksi read-back", "Tekrar.",
               "<p>Talimati cagri ile tekrarla.</p>",
               "AJet 221, taxi holding point 03 via Bravo, hold short.",
               "Dogru read-back?", "Taxi holding point 03 via Bravo, hold short, AJet 221",
               ["Roger", "Cleared for take-off"], 1),
    speak(1, "plt1-hold", "Konus: hold short read-back", "Turkish.",
          "<p>Hold short 03, Turkish 941.</p>",
          "Turkish 941, hold short runway 03.",
          "hold short runway 03 Turkish 941",
          ["holding short 03 thy 941", "hold short 03"],
          "Roger."),
    speak(1, "plt1-lineup", "Konus: line up read-back", "Pegasus.",
          "<p>Line up and wait 03.</p>",
          "Pegasus 12, line up and wait runway 03.",
          "line up and wait runway 03 Pegasus 12",
          ["lining up runway 03", "line up and wait 03"],
          "Roger."),
    scene(1, "plt1-not-to", "Senaryo: henuz kalkma", "Line up.",
          "<p>Line up geldi, take-off degil.</p>",
          "SunExpress 773, line up and wait runway 03.",
          "Line up and wait runway 03, SunExpress 773",
          ["Cleared for take-off, SunExpress 773", "Going around"],
          0, "line up and wait runway 03 SunExpress 773", "Roger."),
    speak(1, "plt1-to", "Konus: take-off read-back", "AJet.",
          "<p>Cleared for take-off 03.</p>",
          "AJet 221, runway 03, cleared for take-off.",
          "cleared for take-off runway 03 AJet 221",
          ["cleared for takeoff anadolu 221", "cleared for take-off 03"],
          "Roger."),
    plt_listen(1, "plt1-land-q", "Dinle: inis izni", "Cleared to land.",
               "<p>Wind + runway + cleared to land.</p>",
               "Turkish 1452, wind 040/8, runway 05, cleared to land.",
               "Ne yapacaksin?", "Inis iznini read-back", ["Go around hemen", "Hold short"], 2),
    speak(1, "plt1-land", "Konus: land read-back", "Turkish 1452.",
          "<p>Cleared to land 05.</p>",
          "Turkish 1452, runway 05, cleared to land.",
          "cleared to land runway 05 Turkish 1452",
          ["cleared to land 05 thy 1452", "cleared to land"],
          "Roger."),
    speak(1, "plt1-vacate", "Konus: vacated", "Bravo.",
          "<p>Runway vacated.</p>",
          "You left 05 on Bravo. Call tower.",
          "Turkish 102J vacated runway 05",
          ["runway vacated", "thy 102 juliet vacated"],
          "Turkish 102J, contact ground."),
    speak(1, "plt1-charlie", "Konus: via Charlie", "Alfabe.",
          "<p>Taxi via Charlie.</p>",
          "Ground: taxi via Charlie, hold short 03.",
          "taxi via Charlie",
          ["taxi via charli", "charlie"],
          "Taxi via Charlie."),
    scene(1, "plt1-anadolu", "Senaryo: AJet soyle", "Okunus.",
          "<p>Cagri isaretin AJet 221 = Anadolu 221.</p>",
          "Ilk cagri, stand 14, push.",
          "Ankara Tower, AJet 221, stand 14, request push and start",
          ["Ankara Tower, SunExpress 221, request landing", "MAYDAY"],
          1, "Ankara Tower AJet 221 request push", "Push approved."),
    plt_listen(1, "plt1-sxs", "Dinle: SunExpress", "SXS.",
               "<p>Sun express.</p>",
               "SunExpress 773, taxi via Alpha.",
               "Sirket?", "SunExpress", ["Pegasus", "THY"], 0),
    speak(1, "plt1-ready", "Konus: ready", "Holding.",
          "<p>Ready for departure.</p>",
          "Checks done, holding point 03.",
          "Turkish 941 ready for departure",
          ["ready for departure thy 941", "ready for departure"],
          "Turkish 941, line up and wait."),
    speak(1, "plt1-abc", "Konus: Alpha Bravo Charlie", "Harfler.",
          "<p>Alfa Bravo Charli.</p>",
          "Say A B C.",
          "Alpha Bravo Charlie",
          ["alfa bravo charli", "alpha bravo"],
          "Alpha Bravo Charlie."),
    scene(1, "plt1-wind", "Senaryo: ruzgari al", "Inis.",
          "<p>Wind 040/8, cleared to land.</p>",
          "AJet 45C, wind 040 degrees 8 knots, runway 05, cleared to land.",
          "Cleared to land runway 05, AJet 45C",
          ["Go around", "Hold short 05"],
          2, "cleared to land runway 05 AJet 45C", "Roger."),
    speak(1, "plt1-ground", "Konus: ground", "Frekans.",
          "<p>Contact ground 121.7.</p>",
          "Tower: contact ground 121.7.",
          "contacting ground 121.7",
          ["contact ground 121 decimal 7", "ground 121.7"],
          "Ground, AJet 221."),
    plt_listen(1, "plt1-hold-q", "Dinle: hold short", "Dur.",
               "<p>Hold short = gecme.</p>",
               "Pegasus 12, hold short runway 03.",
               "Ne yapmazsin?", "Pisti gecmem", ["Hemen kalkarim", "Go around"], 1),
    speak(1, "plt1-juliet", "Konus: 102 Juliet", "Cagri harfi.",
          "<p>102J = Juliet.</p>",
          "You are Turkish 102J.",
          "Ground Turkish 102J request taxi",
          ["thy 102 juliet request taxi", "turkish 102 juliet taxi"],
          "Taxi via Charlie, Turkish 102J."),
]

PILOT.append(content(2, "plt2-intro", "Asama 2: Trafik paterni",
    "Downwind, number 2, final, go around.",
    "<p>Havada kule baska ucaklara da konusur. Number 2'yi anla, extend et, pas gec.</p>"))

PILOT += [
    speak(2, "plt2-downwind", "Konus: downwind", "Pozisyon.",
          "<p>Downwind runway 05.</p>",
          "You are downwind 05.",
          "AJet 221 downwind runway 05",
          ["anadolu 221 downwind 05", "downwind 05"],
          "AJet 221, number 2, report final."),
    plt_listen(2, "plt2-n2", "Dinle: number 2", "Onunde biri.",
               "<p>Continue approach, henuz inis izni yok.</p>",
               "SunExpress 773, number 2, continue approach.",
               "Ne yaparsin?", "Yaklasmaya devam, ikinci siradasin", ["Kalkis", "Pistte dur"], 0),
    speak(2, "plt2-extend", "Konus: extending", "Read-back.",
          "<p>Extending downwind.</p>",
          "Turkish 1452, extend downwind.",
          "extending downwind Turkish 1452",
          ["extend downwind thy 1452", "extending downwind"],
          "Roger."),
    speak(2, "plt2-final", "Konus: final", "Rapor.",
          "<p>Final runway 05.</p>",
          "Turning final 05.",
          "Pegasus 12 final runway 05",
          ["final 05 pegasus 12", "final runway 05"],
          "Pegasus 12, cleared to land."),
    scene(2, "plt2-ga", "Senaryo: go around", "Pist mesgul.",
          "<p>Go around, I say again, go around.</p>",
          "SunExpress 773, go around, traffic on the runway.",
          "Going around, SunExpress 773",
          ["Cleared to land, SunExpress 773", "Hold short"],
          2, "going around SunExpress 773", "Roger, SunExpress 773."),
    speak(2, "plt2-ga-rb", "Konus: going around", "Pas gec.",
          "<p>Going around.</p>",
          "AJet 221, go around.",
          "going around AJet 221",
          ["go around anadolu 221", "going around"],
          "Roger, AJet 221."),
    speak(2, "plt2-orbit", "Konus: orbiting", "Tur.",
          "<p>Orbiting left.</p>",
          "Turkish 941, orbit left.",
          "orbiting left Turkish 941",
          ["orbit left thy 941", "orbiting left"],
          "Roger."),
    plt_listen(2, "plt2-wake", "Dinle: wake", "777 arkasi.",
               "<p>Caution wake turbulence.</p>",
               "AJet 221, caution wake turbulence, number 2.",
               "Ne dikkat?", "Iz turbulansi", ["Yakit", " squawk"], 1),
    speak(2, "plt2-traffic-in-sight", "Konus: traffic in sight", "Gordum.",
          "<p>Traffic in sight.</p>",
          "AJet 221, traffic Airbus on final.",
          "traffic in sight AJet 221",
          ["traffic in sight", "anadolu 221 traffic in sight"],
          "Roger."),
    scene(2, "plt2-num1", "Senaryo: number 1", "Sira geldi.",
          "<p>Number 1, report final.</p>",
          "SunExpress 773, number 1, report final.",
          "Number 1, report final, SunExpress 773",
          ["Going around now", "Request push"],
          0, "number 1 SunExpress 773", "Roger."),
    speak(2, "plt2-continue", "Konus: continuing", "Yaklasma.",
          "<p>Continuing approach.</p>",
          "Pegasus 12, continue approach.",
          "continuing approach Pegasus 12",
          ["continue approach", "continuing approach"],
          "Roger."),
    speak(2, "plt2-wyz", "Konus: Whiskey Yankee Zulu", "Harfler.",
          "<p>Viski, Yanki, Zulu.</p>",
          "Say W Y Z.",
          "Whiskey Yankee Zulu",
          ["viski yanki zulu", "whiskey yankee"],
          "Whiskey Yankee Zulu."),
    plt_listen(2, "plt2-behind", "Dinle: behind landing", "Kalkis.",
               "<p>Behind landing, cleared for take-off.</p>",
               "Turkish 941, behind landing A320, cleared for take-off.",
               "Ne zaman kalkarsin?", "Inen A320'den sonra", ["Hemen simdi uzerinden", "Hicbir zaman"], 2),
    speak(2, "plt2-behind-rb", "Konus: behind landing", "Read-back.",
          "<p>Behind landing, cleared for take-off.</p>",
          "Turkish 941, behind landing, cleared for take-off 03.",
          "behind landing cleared for take-off Turkish 941",
          ["cleared for take-off behind landing", "cleared for take-off 03"],
          "Roger."),
    scene(2, "plt2-two-hear", "Senaryo: kule iki ucaga", "Dinle.",
          "<p>Kule: SunExpress land, sana extend.</p>",
          "Tower: SunExpress 773, cleared to land. AJet 221, extend downwind.",
          "Extending downwind, AJet 221",
          ["Cleared to land, AJet 221", "Going around for SunExpress"],
          1, "extending downwind AJet 221", "Roger."),
    speak(2, "plt2-giveway-rb", "Konus: giving way", "Yol ver.",
          "<p>Giving way.</p>",
          "AJet 221, give way to Pegasus 12.",
          "giving way AJet 221",
          ["giving way anadolu 221", "giving way"],
          "Roger."),
]

PILOT.append(content(3, "plt3-intro", "Asama 3: PAN PAN",
    "Medical, yakit, kus, radyo.",
    "<p>PAN PAN uc kez, sonra cagri, sonra sorun. Kule oncelik verir. MAYDAY degil.</p>"))

PILOT += [
    plt_listen(3, "plt3-pan-q", "Dinle: PAN", "Acil.",
               "<p>Hayat yok, acil var.</p>",
               "PAN PAN PAN, AJet 221, medical on board.",
               "Ne cagri?", "PAN, oncelik istenir", ["Rutin", "Ucak dustu"], 2),
    speak(3, "plt3-pan-med", "Konus: PAN medical", "Anadolu.",
          "<p>PAN PAN PAN, medical, priority landing.</p>",
          "Passenger medical, need the field.",
          "PAN PAN PAN AJet 221 medical request priority landing",
          ["pan pan anadolu 221 medical", "pan pan pan medical"],
          "AJet 221, roger PAN, runway 05."),
    speak(3, "plt3-pan-fuel", "Konus: PAN fuel", "Minimum fuel.",
          "<p>PAN PAN, minimum fuel.</p>",
          "Fuel tight, request immediate landing.",
          "PAN PAN PAN Turkish 1452 minimum fuel",
          ["pan pan minimum fuel", "pan pan thy 1452"],
          "Turkish 1452, roger PAN, number 1."),
    scene(3, "plt3-bird", "Senaryo: bird strike", "Donus.",
          "<p>Kus carpisi, donmek istiyorsun.</p>",
          "After take-off, bird strike, engine running, you want return.",
          "PAN PAN PAN, Pegasus 12, bird strike, request return",
          ["MAYDAY MAYDAY, crashing now", "Roger, continue climb"],
          0, "PAN PAN Pegasus 12 bird strike request return",
          "Pegasus 12, turn back, runway 03."),
    speak(3, "plt3-return", "Konus: returning", "Read-back.",
          "<p>Turning back, runway 03.</p>",
          "Pegasus 12, turn back, runway 03, cleared to land.",
          "turning back cleared to land runway 03 Pegasus 12",
          ["turning back cleared to land", "cleared to land 03"],
          "Roger."),
    speak(3, "plt3-sayagain", "Konus: say again", "Duymadin.",
          "<p>Say again.</p>",
          "Tower garbled.",
          "say again AJet 221",
          ["say again anadolu 221", "say again"],
          "AJet 221, taxi via Bravo."),
    plt_listen(3, "plt3-delay", "Dinle: delay", "Bekle.",
               "<p>Delay 10 minutes.</p>",
               "SunExpress 773, delay 10 minutes due traffic.",
               "Ne olur?", "10 dakika gecikme", ["Hemen in", "Mayday"], 1),
    scene(3, "plt3-unable", "Senaryo: unable", "Kule kalkis vermiyor.",
          "<p>Unable immediate departure.</p>",
          "You are ready. Tower: unable, inbound 3 miles, hold position.",
          "Holding position, SunExpress 773",
          ["Cleared for take-off anyway", "MAYDAY"],
          2, "holding position SunExpress 773", "Roger."),
    speak(3, "plt3-hold", "Konus: holding Golf", "Yogun.",
          "<p>Holding at Golf.</p>",
          "Pegasus 12, hold at Golf.",
          "holding at Golf Pegasus 12",
          ["holding golf", "hold at golf"],
          "Roger."),
    speak(3, "plt3-priority-rb", "Konus: priority read-back", "PAN cevap.",
          "<p>Number 1, priority, cleared to land.</p>",
          "AJet 221, number 1, priority, cleared to land 05.",
          "number 1 priority cleared to land AJet 221",
          ["cleared to land priority anadolu 221", "cleared to land 05"],
          "Roger."),
    plt_listen(3, "plt3-7600", "Dinle: 7600", "Radyo.",
               "<p>Squawk 7600.</p>",
               "If radio dies: squawk 7600, look for light signals.",
               "7600 nedir?", "Radyo arizasi", ["Genel acil 7700", "Korsanlik"], 0),
    scene(3, "plt3-medical-land", "Senaryo: ambulans", "Inis sonrasi.",
          "<p>PAN medical landed.</p>",
          "You landed 05 with medical. Tower: taxi Bravo, ambulance rolling.",
          "Taxi Bravo, ambulance rolling, AJet 221",
          ["Going around", "Request take-off"],
          1, "taxi Bravo ambulance AJet 221", "Roger."),
    speak(3, "plt3-ident", "Konus: ident", "Radar.",
          "<p>Ident.</p>",
          "SunExpress 773, squawk ident.",
          "ident SunExpress 773",
          ["squawk ident sun express", "ident"],
          "Roger."),
    speak(3, "plt3-wet", "Konus: wet runway", "Caution.",
          "<p>Caution wet runway, cleared to land.</p>",
          "AJet 221, caution wet runway, cleared to land 05.",
          "cleared to land runway 05 caution wet AJet 221",
          ["cleared to land wet runway", "cleared to land 05"],
          "Roger."),
    scene(3, "plt3-break", "Senaryo: break", "Ust uste.",
          "<p>Kule break break dedi, PAN var.</p>",
          "You were calling taxi. Tower: break break, Turkish 941 go ahead.",
          "Standing by, AJet 221",
          ["Keep talking over the MAYDAY", "Cleared for take-off"],
          0, "standing by AJet 221", "Roger."),
    speak(3, "plt3-standby-rb", "Konus: standing by", "Bekle.",
          "<p>Standing by.</p>",
          "AJet 221, standby.",
          "standing by AJet 221",
          ["standby anadolu 221", "standing by"],
          "Roger."),
]

PILOT.append(content(4, "plt4-intro", "Asama 4: MAYDAY",
    "Motor, basinc, hidrolik. Kule souls, yakit, kargo sorar.",
    "<p>MAYDAY uc kez. Sonra niyet. Kule pist verir, souls / fuel / dangerous goods sorar. Cevapla.</p>"))

PILOT += [
    speak(4, "plt4-mayday", "Konus: MAYDAY motor", "Hayat.",
          "<p>MAYDAY MAYDAY MAYDAY, engine failure.</p>",
          "Engine failure, need the field.",
          "MAYDAY MAYDAY MAYDAY AJet 221 engine failure",
          ["mayday anadolu 221 engine failure", "mayday mayday engine failure"],
          "AJet 221, roger MAYDAY, runway 03 is yours."),
    plt_listen(4, "plt4-yours", "Dinle: runway yours", "Pist senin.",
               "<p>Services rolling.</p>",
               "AJet 221, roger MAYDAY, runway 03 is yours, services rolling.",
               "Ne var?", "Pist ve acil ekipler", ["Taksi Golf", "Delay 10"], 2),
    speak(4, "plt4-souls", "Konus: souls", "148.",
          "<p>148 souls, fuel 2 hours, no dangerous goods.</p>",
          "Tower: souls on board, fuel remaining, dangerous goods?",
          "148 souls fuel 2 hours no dangerous goods",
          ["148 souls", "no dangerous goods fuel 2 hours"],
          "Roger."),
    scene(4, "plt4-hydro", "Senaryo: hidrolik", "Foam.",
          "<p>MAYDAY hydraulic, foam.</p>",
          "Gear uncertain. Tower offers 03 and foam.",
          "MAYDAY MAYDAY MAYDAY, SunExpress 773, hydraulic, request foam runway 03",
          ["Request taxi to stand", "PAN PAN, coffee spill"],
          1, "MAYDAY SunExpress 773 hydraulic request foam",
          "Foam standing by, SunExpress 773."),
    speak(4, "plt4-press", "Konus: decompression", "Alcalis.",
          "<p>MAYDAY, cabin decompression, emergency descent.</p>",
          "Cabin altitude high, masks, need 03.",
          "MAYDAY MAYDAY MAYDAY Turkish 1452 decompression emergency descent",
          ["mayday decompression", "mayday thy 1452 emergency descent"],
          "Turkish 1452, descend, runway 03 yours."),
    speak(4, "plt4-7700", "Konus: squawk 7700", "Kod.",
          "<p>Squawk 7700.</p>",
          "Tower: squawk 7700.",
          "squawk 7700 AJet 221",
          ["squawk 7700", "7700 anadolu 221"],
          "Roger."),
    plt_listen(4, "plt4-goods-q", "Dinle: kargo sorusu", "DG.",
               "<p>Any dangerous goods?</p>",
               "Pegasus 12, any dangerous goods?",
               "Ne cevaplarsin?", "Varsa madde, yoksa none", ["Pist numarasi", "Yemek siparisi"], 0),
    speak(4, "plt4-none", "Konus: no dangerous goods", "Kargo yok.",
          "<p>No dangerous goods.</p>",
          "Tower: dangerous goods?",
          "no dangerous goods Pegasus 12",
          ["no dangerous goods", "none"],
          "Roger."),
    scene(4, "plt4-evac", "Senaryo: tahliye", "Smoke.",
          "<p>Stopped on 03, smoke, evacuate.</p>",
          "Tower: evacuate on the runway, services with you.",
          "Evacuating on the runway, AJet 221",
          ["Request take-off", "Taxi to gate with smoke"],
          2, "evacuating on the runway AJet 221", "Roger."),
    speak(4, "plt4-evac", "Konus: evacuating", "Pistte.",
          "<p>Evacuating on the runway.</p>",
          "AJet 221, evacuate on the runway, services with you.",
          "evacuating on the runway AJet 221",
          ["evacuating", "anadolu 221 evacuating"],
          "Roger."),
    speak(4, "plt4-gear", "Konus: gear down", "Teyit.",
          "<p>Gear down.</p>",
          "SunExpress 773, confirm gear down.",
          "gear down SunExpress 773",
          ["gear down", "sun express gear down"],
          "Roger."),
    plt_listen(4, "plt4-foam", "Dinle: foam", "Itfaiye.",
               "<p>Foam standing by.</p>",
               "SunExpress 773, foam standing by, runway 03.",
               "Kim hazir?", "Itfaiye kopugu", ["Catering", "Pushback"], 1),
    scene(4, "plt4-full", "Senaryo: kule her seyi sordu", "Cevap paketi.",
          "<p>Souls, fuel, cargo tek seferde.</p>",
          "Tower: souls, fuel remaining, dangerous goods?",
          "90 souls, fuel 25 minutes, no dangerous goods, Pegasus 12",
          ["Roger only", "Request coffee"],
          0, "90 souls fuel 25 minutes no dangerous goods", "Roger."),
    speak(4, "plt4-full", "Konus: souls fuel goods", "Tek nefes.",
          "<p>90 souls, fuel 25 minutes, no dangerous goods.</p>",
          "Tower wants the three numbers.",
          "90 souls fuel 25 minutes no dangerous goods",
          ["90 souls no dangerous goods", "fuel 25 minutes"],
          "Roger, Pegasus 12."),
    live(4, "plt4-ivao", "Canli: IVAO PP", "Hatti bitirdin.",
         "<p>Giris yapanlar: puan dolunca IVAO'da gercek ATC ile dene. Once dinle, sonra C172 circuit.</p>"),
]


def emit(path_slug: str, rows: list, start_order: int) -> list[str]:
    lines = []
    order = start_order
    for kind, slug, title, desc, html, conf in rows:
        lines.append(
            "INSERT INTO learning_steps (path_id, title, slug, description, step_type, content_html, configuration, order_index, required, status)\n"
            f"SELECT id, {q(title)}, {q(slug)}, {q(desc)}, {q(kind)}, {q(html)}, {cfg(conf)}, {order}, TRUE, 'PUBLISHED' "
            f"FROM learning_paths WHERE slug = {q(path_slug)}\n"
            f"AND NOT EXISTS (SELECT 1 FROM learning_steps WHERE slug = {q(slug)});\n"
        )
        order += 1
    return lines


parts = [
    "-- Dort asama kule + pilot pratik. Eski dinle/konus/senaryo arsivlenir.\n",
    "UPDATE learning_steps SET status = 'ARCHIVED'\n",
    " WHERE path_id IN (SELECT id FROM learning_paths WHERE slug IN ('kule-ol', 'pilot-ol'))\n",
    "   AND step_type IN ('LISTEN', 'SPEAK', 'SCENARIO', 'LIVE_PRACTICE', 'PRACTICE')\n",
    "   AND status = 'PUBLISHED';\n\n",
    "UPDATE learning_steps SET configuration = coalesce(configuration, '{}'::jsonb) || '{\"stage\":1}'::jsonb\n",
    " WHERE slug IN ('kule-kimdir', 'turkiyede-atc', 'ivao-rating', 'twr-alfabe',\n",
    "                'dinle-ilk-cagri-pilot', 'plt-alfabe') AND status = 'PUBLISHED';\n\n",
    "UPDATE learning_paths SET description = 'Dort asama: zemin, trafik, PAN, MAYDAY. Yaklasik 100 pratik. Giris yapan puan biriktirir.'\n",
    " WHERE slug = 'kule-ol';\n",
    "UPDATE learning_paths SET description = 'Dort asama: yer, patern, PAN, MAYDAY. Read-back ve acil cagri. Giris yapan puan biriktirir.'\n",
    " WHERE slug = 'pilot-ol';\n\n",
]
parts += emit("kule-ol", TOWER, 100)
parts.append("\n")
parts += emit("pilot-ol", PILOT, 100)

OUT.write_text("".join(parts), encoding="utf-8")
print("tower", len(TOWER), "pilot", len(PILOT), "->", OUT)
