CREATE TABLE aircraft (
    id              BIGSERIAL PRIMARY KEY,
    code            VARCHAR(16) NOT NULL,
    name            VARCHAR(120) NOT NULL,
    manufacturer    VARCHAR(40) NOT NULL,
    philosophy      TEXT,
    sort_index      INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_aircraft_code UNIQUE (code)
);

CREATE TABLE cockpit_parts (
    id              BIGSERIAL PRIMARY KEY,
    aircraft_id     BIGINT NOT NULL REFERENCES aircraft (id) ON DELETE CASCADE,
    code            VARCHAR(32) NOT NULL,
    panel           VARCHAR(80) NOT NULL,
    name_en         VARCHAR(200) NOT NULL,
    name_tr         VARCHAR(200) NOT NULL,
    location        VARCHAR(240) NOT NULL,
    function_tr     TEXT NOT NULL,
    category        VARCHAR(64) NOT NULL,
    sort_index      INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_cockpit_parts_code UNIQUE (code)
);
CREATE INDEX idx_cockpit_parts_aircraft ON cockpit_parts (aircraft_id);
CREATE INDEX idx_cockpit_parts_panel ON cockpit_parts (aircraft_id, panel);

CREATE TABLE user_part_progress (
    id              BIGSERIAL PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users (id),
    part_id         BIGINT NOT NULL REFERENCES cockpit_parts (id) ON DELETE CASCADE,
    status          VARCHAR(20) NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_user_part_progress UNIQUE (user_id, part_id),
    CONSTRAINT ck_user_part_progress_status CHECK (status IN ('LEARNED'))
);

CREATE TABLE training_simulations (
    id              BIGSERIAL PRIMARY KEY,
    aircraft_id     BIGINT NOT NULL REFERENCES aircraft (id) ON DELETE CASCADE,
    code            VARCHAR(40) NOT NULL,
    title           VARCHAR(200) NOT NULL,
    description     TEXT NOT NULL,
    sim_type        VARCHAR(24) NOT NULL,
    config          JSONB NOT NULL,
    CONSTRAINT uk_training_simulations_code UNIQUE (code),
    CONSTRAINT ck_training_simulations_type CHECK (sim_type IN ('TUTORIAL','SHORT_FLIGHT','FAILURE','CRASH_DRILL'))
);

CREATE TABLE simulation_sessions (
    id              BIGSERIAL PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users (id),
    simulation_id   BIGINT NOT NULL REFERENCES training_simulations (id),
    status          VARCHAR(20) NOT NULL,
    state           JSONB NOT NULL,
    last_message    TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_simulation_sessions_status CHECK (status IN ('IN_PROGRESS','PASSED','CRASHED','FAILED'))
);

INSERT INTO aircraft (code, name, manufacturer, philosophy, sort_index) VALUES ('B737', 'Boeing 737 NG/MAX', 'BOEING', 'Konvansiyonel yoke/kolon kontrolü, kablo/hidrolik destekli kontrol yüzeyleri, Boeing otomasyon felsefesi', 1);

INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-001', 'Overhead Panel', 'Electrical Panel (GEN, APU GEN, BAT, EXT PWR)', 'Elektrik Paneli', 'Tavan paneli, sol bölüm', 'Jeneratörler, batarya ve harici güç kaynağının kontrolü', 'Electrical', 0 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-002', 'Overhead Panel', 'Hydraulic Panel (A/B System Pumps)', 'Hidrolik Paneli', 'Tavan paneli, orta bölüm', 'A ve B hidrolik sistemlerinin elektrikli ve motor tahrikli pompa kontrolü', 'Hydraulics', 1 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-003', 'Overhead Panel', 'Fuel Panel (Pumps, Crossfeed)', 'Yakıt Paneli', 'Tavan paneli, orta bölüm', 'Yakıt pompaları ve çapraz besleme (crossfeed) vanası kontrolü', 'Fuel', 2 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-004', 'Overhead Panel', 'Air Conditioning/Pressurization Panel', 'Klima ve Basınçlandırma Paneli', 'Tavan paneli, sağ bölüm', 'Kabin sıcaklığı, paket (pack) kontrolü ve basınçlandırma ayarları', 'Environmental', 3 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-005', 'Overhead Panel', 'Anti-Ice Panel (Wing, Engine)', 'Buzlanma Önleme Paneli', 'Tavan paneli, sağ bölüm', 'Kanat ve motor giriş buzlanma önleme sistemlerinin kontrolü', 'Anti-Ice', 4 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-006', 'Overhead Panel', 'APU Panel', 'Yardımcı Güç Ünitesi Paneli', 'Tavan paneli, orta bölüm', 'APU çalıştırma/durdurma kontrolü', 'APU', 5 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-007', 'Overhead Panel', 'Engine Start Panel', 'Motor Çalıştırma Paneli', 'Tavan paneli, orta bölüm', 'Motor çalıştırma modunun (GRD, CONT, FLT) seçimi', 'Engine', 6 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-008', 'Overhead Panel', 'Exterior Lights Panel', 'Dış Işık Paneli', 'Tavan paneli, ön bölüm', 'İniş, taksi, navigasyon, strobe ve beacon ışıklarının kontrolü', 'Lighting', 7 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-009', 'Overhead Panel', 'Fire Protection Panel (Engine/APU Fire)', 'Yangın Koruma Paneli', 'Tavan paneli, orta-alt bölüm, kırmızı korumalı', 'Motor ve APU yangın algılama, kesme ve söndürme kontrolü', 'Fire Protection', 8 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-010', 'Overhead Panel', 'Oxygen Panel', 'Oksijen Paneli', 'Tavan paneli, sol ön bölüm', 'Kokpit ekibi oksijen basıncı göstergesi ve kontrolü', 'Oxygen', 9 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-011', 'Glareshield', 'MCP - Mode Control Panel', 'Mod Kontrol Paneli', 'Gösterge panelinin üstü, ortada', 'Otopilot, oto-itki ve uçuş yönlendirici modlarının seçildiği ana panel', 'Autoflight', 10 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-012', 'Glareshield', 'Course Selector Knob', 'Rota Seçici Düğme', 'MCP üzerinde, sol ve sağ uçlar', 'VOR/ILS rotasının (course) belirlenmesi', 'Autoflight', 11 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-013', 'Glareshield', 'Heading Selector Knob', 'Kalkış Açısı Seçici Düğme', 'MCP üzerinde sol-orta', 'Hedef uçuş yönünün (heading) girilmesi', 'Autoflight', 12 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-014', 'Glareshield', 'Altitude Selector Window', 'İrtifa Seçici Pencere', 'MCP üzerinde sağ-orta', 'Hedef irtifanın girilmesi', 'Autoflight', 13 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-015', 'Glareshield', 'IAS/MACH Selector Window', 'Hız/Mach Seçici Pencere', 'MCP üzerinde sol taraf', 'Otopilot/oto-itki için hedef hız girişi', 'Autoflight', 14 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-016', 'Glareshield', 'V/S Thumbwheel', 'Dikey Hız Ayar Çarkı', 'MCP üzerinde sağ taraf', 'Tırmanış/alçalış oranının manuel ayarlanması', 'Autoflight', 15 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-017', 'Glareshield', 'LVL CHG Pushbutton', 'Seviye Değişim Butonu', 'MCP üzerinde', 'Hız korunarak irtifa değişimi yapan otomatik uçuş modu', 'Autoflight', 16 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-018', 'Glareshield', 'VNAV Pushbutton', 'Dikey Navigasyon Butonu', 'MCP üzerinde', 'FMC tarafından hesaplanan dikey profilin otomatik takibi', 'Autoflight', 17 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-019', 'Glareshield', 'LNAV Pushbutton', 'Yatay Navigasyon Butonu', 'MCP üzerinde', 'FMC rotasının yatay düzlemde otomatik takibi', 'Autoflight', 18 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-020', 'Glareshield', 'A/P Engage Switches (CMD A/B)', 'Otopilot Devreye Alma Anahtarları', 'MCP üzerinde, sağ bölüm', 'Otopilot A veya B kanalının devreye alınması', 'Autoflight', 19 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-021', 'Glareshield', 'A/T Arm Switch', 'Oto-İtki Hazırlama Anahtarı', 'MCP üzerinde', 'Oto-itki sisteminin hazır (armed) konuma alınması', 'Autoflight', 20 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-022', 'Glareshield', 'LOC/APP Pushbuttons', 'Localizer/Yaklaşma Butonları', 'MCP üzerinde', 'ILS yaklaşma modlarının devreye alınması', 'Autoflight', 21 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-023', 'Main Instrument Panel', 'PFD - Primary Flight Display', 'Ana Uçuş Göstergesi', 'Pilot/co-pilot önünde, iç taraf', 'Hız, tutum, irtifa, dikey hız ve FMA gösterimi', 'Displays', 22 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-024', 'Main Instrument Panel', 'ND - Navigation Display', 'Navigasyon Göstergesi', 'Pilot/co-pilot önünde, dış taraf', 'Rota, waypoint, hava radarı ve trafik bilgisi gösterimi', 'Displays', 23 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-025', 'Main Instrument Panel', 'Upper EICAS/Engine Display', 'Üst Motor Göstergesi (EICAS benzeri)', 'Orta panel, üst ekran', 'Motor N1/N2, EGT, yakıt akışı gibi birincil motor parametrelerinin gösterimi', 'Displays', 24 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-026', 'Main Instrument Panel', 'Lower Display Unit', 'Alt Gösterge Ünitesi', 'Orta panel, alt ekran', 'İkincil motor parametreleri, hidrolik/elektrik/yakıt durum bilgisi', 'Displays', 25 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-027', 'Main Instrument Panel', 'Standby Flight Instruments', 'Yedek Uçuş Göstergeleri', 'Orta panel, PFD''lerin arasında', 'Ana göstergeler arızalandığında kullanılan bağımsız yedek hız/tutum/irtifa göstergesi', 'Standby Instruments', 26 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-028', 'Pedestal', 'Thrust Levers', 'İtki Kolları', 'Pedestal, ön-orta bölüm', 'Motor itkisinin manuel kontrolü; Boeing''de oto-itki aktifken kollar fiziksel olarak hareket eder', 'Engine Control', 27 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-029', 'Pedestal', 'Speed Brake Lever', 'Hava Freni Kolu', 'Pedestal, itki kollarının arkası/ortası', 'Spoiler''ların hava freni olarak devreye alınması', 'Flight Controls', 28 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-030', 'Pedestal', 'Flap Lever', 'Flap Kolu', 'Pedestal, sol taraf', 'Kalkış/iniş için flap pozisyonlarının kademeli seçimi (1-40 arası konumlar)', 'Flight Controls', 29 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-031', 'Pedestal', 'Stabilizer Trim Wheel', 'Yatay Dengeleyici Trim Çarkı', 'Pedestal, iki taraf, büyük fiziksel çark', 'Yatay dengeleyicinin (stabilizer) manuel veya elektrikli trim ayarı; Boeing''e özgü belirgin büyük çark', 'Flight Controls', 30 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-032', 'Pedestal', 'Parking Brake Handle', 'Park Freni Kolu', 'Pedestal, ön bölüm, kolon altı', 'Uçağı yerde sabit tutmak için fren sisteminin kilitlenmesi', 'Brakes', 31 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-033', 'Pedestal', 'CDU - Control Display Unit', 'Kontrol Gösterge Ünitesi', 'Pedestal, sol ve sağ taraf', 'FMC (Flight Management Computer) ile uçuş planı ve performans veri girişi', 'FMS', 32 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-034', 'Pedestal', 'Radio Panel (VHF COMM/NAV)', 'Telsiz Paneli', 'Pedestal, ön bölüm', 'VHF telsiz ve navigasyon frekanslarının seçimi', 'Communications', 33 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-035', 'Control Column', 'Control Yoke/Column', 'Kumanda Yoku/Kolonu', 'Pilot/co-pilot önünde, direksiyon benzeri', 'Uçağın yunuslama (pitch) ve yatış (roll) hareketlerinin mekanik/hidrolik kontrolü', 'Flight Controls', 34 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-036', 'Control Column', 'Trim Switches (Yoke-mounted)', 'Yok Üzeri Trim Anahtarları', 'Yokun sol tarafında, başparmak ile erişilir', 'Elektrikli yatay dengeleyici trim ayarı', 'Flight Controls', 35 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-037', 'Control Column', 'Control Wheel Disconnect / A/P Disengage Switch', 'Otopilot Ayırma Anahtarı', 'Yok üzerinde, sol taraf', 'Otopilotu anında devre dışı bırakma', 'Autoflight', 36 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-038', 'Floor/Pedals', 'Rudder Pedals', 'Yön Dümeni Pedalları', 'Pilot/co-pilot ayak altı', 'Uçağın sapma (yaw) hareketinin kontrolü; aynı zamanda tekerlek direksiyonu (nose wheel steering) ve fren işlevi görür', 'Flight Controls', 37 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-039', 'Main Instrument Panel', 'Landing Gear Lever', 'İniş Takımı Kolu', 'Orta panel, alt kısım', 'İniş takımının indirilip kaldırılması', 'Landing Gear', 38 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-040', 'Main Instrument Panel', 'Autobrake Selector', 'Otomatik Fren Seçici', 'İniş takımı kolu yakınında', 'İniş sonrası otomatik fren şiddetinin seçimi (1-3, MAX AUTO/RTO)', 'Brakes', 39 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-041', 'Main Instrument Panel', 'Weather Radar Panel', 'Hava Radarı Paneli', 'Pedestal üstü/orta panel', 'Hava radarı modu ve kapsama ayarları', 'Navigation', 40 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-042', 'Overhead Panel', 'Standby Power Panel', 'Yedek Güç Paneli', 'Tavan paneli, sol bölüm', 'Ana elektrik sistemi arızalandığında yedek batarya devresinin kontrolü', 'Electrical', 41 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-043', 'Main Instrument Panel', 'Cabin Altitude/Pressure Gauge', 'Kabin İrtifa/Basınç Göstergesi', 'Alt gösterge veya ayrı analog gösterge (eski nesillerde)', 'Kabin irtifası ve fark basıncının gösterimi', 'Environmental', 42 FROM aircraft WHERE code = 'B737';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'B737-044', 'Pedestal', 'ATC/TCAS Panel', 'ATC Transponder/TCAS Paneli', 'Pedestal, ön bölüm', 'Transponder kodu girişi ve TCAS modu seçimi', 'Surveillance', 43 FROM aircraft WHERE code = 'B737';

INSERT INTO aircraft (code, name, manufacturer, philosophy, sort_index) VALUES ('A350', 'Airbus A350-900/-1000', 'AIRBUS', 'Fly-by-wire, side-stick, dual FMS ile Airbus otomasyon felsefesi', 2);

INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-001', 'Overhead Panel', 'ELEC Panel (GEN 1/2/APU GEN, EXT PWR, BAT 1/2)', 'Elektrik Paneli', 'Tavan paneli, sol-orta bölüm', 'Jeneratörler, harici güç ve bataryaların açma/kapama ve durum kontrolü', 'Electrical', 0 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-002', 'Overhead Panel', 'HYD Panel (Green/Yellow ELEC PUMP)', 'Hidrolik Paneli', 'Tavan paneli, orta bölüm', 'Hidrolik pompaların kontrolü; A350''de klasik 3 hidrolik hat yerine elektrikli yedek pompalar bulunur', 'Hydraulics', 1 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-003', 'Overhead Panel', 'FUEL Panel (Pumps, X-FEED, Jettison)', 'Yakıt Paneli', 'Tavan paneli, orta bölüm', 'Yakıt pompaları, çapraz besleme (crossfeed) ve yakıt boşaltma (jettison) kontrolü', 'Fuel', 2 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-004', 'Overhead Panel', 'AIR COND/PRESS Panel', 'Klima ve Kabin Basınç Paneli', 'Tavan paneli, sağ bölüm', 'Kabin sıcaklığı, klima paketleri (packs) ve kabin basınçlandırma kontrolü', 'Environmental', 3 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-005', 'Overhead Panel', 'ANTI ICE Panel (Wing, Eng 1/2, Probe Heat)', 'Buzlanma Önleme Paneli', 'Tavan paneli, sağ bölüm', 'Kanat, motor giriş ağzı ve sensör ısıtma sistemlerinin kontrolü', 'Anti-Ice', 4 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-006', 'Overhead Panel', 'APU Panel (MASTER SW, START)', 'Yardımcı Güç Ünitesi Paneli', 'Tavan paneli, orta bölüm', 'APU''yu çalıştırma/durdurma ve durum göstergesi', 'APU', 5 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-007', 'Overhead Panel', 'ENG Panel (Master 1/2, Manual Start)', 'Motor Paneli', 'Tavan paneli, orta-alt bölüm', 'Motor ana anahtarları ve manuel çalıştırma kontrolü', 'Engine', 6 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-008', 'Overhead Panel', 'EXT LT Panel (Landing, Taxi, Nav, Strobe, Beacon)', 'Dış Işık Paneli', 'Tavan paneli, ön bölüm', 'Uçağın dış aydınlatma sistemlerinin kontrolü', 'Lighting', 7 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-009', 'Overhead Panel', 'OXYGEN Panel (Crew Supply)', 'Oksijen Paneli', 'Tavan paneli, sol ön bölüm', 'Kokpit ekibi oksijen sistemi kontrolü ve basınç göstergesi', 'Oxygen', 8 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-010', 'Overhead Panel', 'CARGO SMOKE Panel', 'Kargo Duman Algılama Paneli', 'Tavan paneli, orta-alt bölüm', 'Kargo bölmesi duman algılama ve söndürme sistemi kontrolü', 'Fire Protection', 9 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-011', 'Overhead Panel', 'ENG FIRE Panel (Master, Discharge)', 'Motor Yangın Paneli', 'Tavan paneli, orta-alt bölüm, kırmızı korumalı', 'Motor yangını durumunda kesme ve söndürücü tetikleme', 'Fire Protection', 10 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-012', 'Glareshield', 'FCU - Flight Control Unit', 'Uçuş Kontrol Ünitesi', 'Gösterge panelinin üstü, ortada', 'Hız/Mach, kalkış açısı (HDG/TRK), irtifa ve V/S/FPA değerlerinin otopilota girilmesi', 'Autoflight', 11 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-013', 'Glareshield', 'SPD/MACH Selector Knob', 'Hız/Mach Seçici Düğme', 'FCU üzerinde sol taraf', 'Otopilot/oto-thrust için hedef hız veya Mach değeri seçimi', 'Autoflight', 12 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-014', 'Glareshield', 'HDG/TRK Selector Knob', 'Kalkış Açısı/Rota Seçici Düğme', 'FCU üzerinde sol-orta', 'Hedef uçuş yönü (heading) veya rota (track) değeri girişi', 'Autoflight', 13 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-015', 'Glareshield', 'ALT Selector Knob', 'İrtifa Seçici Düğme', 'FCU üzerinde sağ-orta', 'Hedef irtifa girişi (feet cinsinden)', 'Autoflight', 14 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-016', 'Glareshield', 'V/S-FPA Selector Knob', 'Dikey Hız/Uçuş Yolu Açısı Seçici', 'FCU üzerinde sağ taraf', 'Tırmanış/alçalış oranı veya uçuş yolu açısının girilmesi', 'Autoflight', 15 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-017', 'Glareshield', 'AP1/AP2 Pushbuttons', 'Otopilot 1/2 Butonları', 'FCU üzerinde ortada', 'Otopilot 1 veya 2''yi devreye alma', 'Autoflight', 16 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-018', 'Glareshield', 'A/THR Pushbutton', 'Oto-İtki Butonu', 'FCU üzerinde ortada', 'Oto-itki (auto-thrust) sistemini devreye alma', 'Autoflight', 17 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-019', 'Glareshield', 'LOC/APPR Pushbuttons', 'Localizer/Yaklaşma Butonları', 'FCU üzerinde ortada', 'ILS localizer takibi veya tam yaklaşma modunu (LOC+G/S) devreye alma', 'Autoflight', 18 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-020', 'Glareshield', 'EXPED Pushbutton', 'Hızlandırılmış Tırmanış/Alçalış Butonu', 'FCU üzerinde', 'Maksimum tırmanış/alçalış oranı ile hızlı irtifa değişimi sağlar', 'Autoflight', 19 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-021', 'Main Instrument Panel', 'PFD - Primary Flight Display', 'Ana Uçuş Göstergesi', 'Pilot/co-pilot önünde, iç taraf', 'Hız, tutum (attitude), irtifa, dikey hız ve FMA (uçuş modu anonsları) gösterimi', 'Displays', 20 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-022', 'Main Instrument Panel', 'ND - Navigation Display', 'Navigasyon Göstergesi', 'Pilot/co-pilot önünde, dış taraf', 'Rota, waypoint, hava radarı ve trafik (TCAS) bilgisinin gösterimi', 'Displays', 21 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-023', 'Main Instrument Panel', 'ECAM Upper Display (E/WD)', 'ECAM Üst Ekran (Motor/Uyarı Göstergesi)', 'Orta panel, üst ekran', 'Motor parametreleri, yakıt miktarı ve uyarı/hata mesajlarının gösterimi', 'Displays', 22 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-024', 'Main Instrument Panel', 'ECAM Lower Display (SD)', 'ECAM Alt Ekran (Sistem Göstergesi)', 'Orta panel, alt ekran (pedestal üstü)', 'Seçilen uçak sisteminin (hidrolik, elektrik, yakıt vb.) şematik gösterimi', 'Displays', 23 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-025', 'Main Instrument Panel', 'ISIS - Integrated Standby Instrument System', 'Entegre Yedek Gösterge Sistemi', 'Orta panel, PFD''lerin arasında, üst kısım', 'Ana ekranlar arızalandığında kullanılan yedek hız/tutum/irtifa göstergesi', 'Standby Instruments', 24 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-026', 'Pedestal', 'Thrust Levers', 'İtki Kolları', 'Pedestal, ön-orta bölüm', 'Motor itkisinin manuel kontrolü; A350''de oto-itki aktifken de sabit pozisyonda kalır (Airbus FADEC mantığı)', 'Engine Control', 25 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-027', 'Pedestal', 'Speed Brake Lever', 'Hava Freni Kolu', 'Pedestal, itki kollarının solunda', 'Kanat üstü spoiler''ların hava freni olarak devreye alınması', 'Flight Controls', 26 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-028', 'Pedestal', 'Flap/Slat Lever', 'Flap/Slat Kolu', 'Pedestal, sol taraf', 'Kalkış ve iniş için kanat flap ve slat pozisyonlarının seçimi', 'Flight Controls', 27 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-029', 'Pedestal', 'Parking Brake Handle', 'Park Freni Kolu', 'Pedestal, ön bölüm', 'Uçağı yerde sabit tutmak için fren sisteminin kilitlenmesi', 'Brakes', 28 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-030', 'Pedestal', 'MCDU - Multipurpose Control and Display Unit', 'Çok Amaçlı Kontrol ve Gösterge Ünitesi', 'Pedestal, sol ve sağ taraf (pilot/co-pilot için ayrı)', 'Uçuş planı, performans hesapları ve FMS veri girişi', 'FMS', 29 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-031', 'Pedestal', 'KCCU - Keyboard Cursor Control Unit', 'Klavye İmleç Kontrol Ünitesi', 'Pedestal, MCDU yanında', 'A350''ye özgü; büyük ekranlarda imleç ile veri girişini sağlar (mouse benzeri kontrol)', 'FMS', 30 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-032', 'Pedestal', 'RMP - Radio Management Panel', 'Radyo Yönetim Paneli', 'Pedestal, ön bölüm', 'VHF/HF telsiz frekanslarının seçimi ve yönetimi', 'Communications', 31 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-033', 'Pedestal', 'Trim Wheel (Manual Pitch Trim)', 'Manuel Yunuslama Trim Çarkı', 'Pedestal, iki taraf', 'Elektrikli trim sistemi arızalandığında manuel yatay dengeleyici (stabilizer) ayarı', 'Flight Controls', 32 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-034', 'Side Console', 'Side Stick', 'Yan Kumanda Kolu', 'Pilot/co-pilot koltuğunun dış tarafı', 'Uçağın yunuslama (pitch) ve yatış (roll) hareketlerinin fly-by-wire ile kontrolü', 'Flight Controls', 33 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-035', 'Side Console', 'Priority Takeover Pushbutton', 'Öncelik Devralma Butonu', 'Side stick üzerinde, kırmızı buton', 'İki pilotun aynı anda kumanda vermesi durumunda birinin kontrolü devralmasını sağlar', 'Flight Controls', 34 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-036', 'Floor/Pedals', 'Rudder Pedals', 'Yön Dümeni Pedalları', 'Pilot/co-pilot ayak altı', 'Uçağın sapma (yaw) hareketinin kontrolü; aynı zamanda yer freni işlevi görür', 'Flight Controls', 35 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-037', 'Main Instrument Panel', 'Landing Gear Lever', 'İniş Takımı Kolu', 'Orta panel, alt kısım', 'İniş takımının indirilip kaldırılması', 'Landing Gear', 36 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-038', 'Main Instrument Panel', 'Autobrake Selector', 'Otomatik Fren Seçici', 'İniş takımı kolu yakınında', 'İniş sonrası otomatik fren şiddetinin seçimi (LOW/MED/MAX)', 'Brakes', 37 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-039', 'Main Instrument Panel', 'Weather Radar Panel', 'Hava Radarı Paneli', 'Pedestal üstü/orta panel', 'Hava radarı modunun (WX, TURB) ve kapsama alanının ayarlanması', 'Navigation', 38 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-040', 'Overhead Panel', 'EMER ELEC PWR Panel', 'Acil Elektrik Güç Paneli', 'Tavan paneli, sol bölüm', 'RAT (Ram Air Turbine) ve acil jeneratör devrelerinin kontrolü', 'Electrical', 39 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-041', 'Main Instrument Panel', 'Cabin Pressure Indicator', 'Kabin Basınç Göstergesi', 'ECAM alt ekranı veya ayrı gösterge', 'Kabin irtifası, fark basıncı ve iniş/çıkış hızının gösterimi', 'Environmental', 40 FROM aircraft WHERE code = 'A350';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'A350-042', 'Pedestal', 'ATC/TCAS Panel', 'ATC Transponder/TCAS Paneli', 'Pedestal, ön bölüm', 'Transponder kodu girişi ve TCAS (çarpışma önleme sistemi) modu seçimi', 'Surveillance', 41 FROM aircraft WHERE code = 'A350';

INSERT INTO aircraft (code, name, manufacturer, philosophy, sort_index) VALUES ('C172', 'Cessna 172 Skyhawk', 'CESSNA', 'Temel eğitim uçağı: mekanik yoke, piston motor, sabit hatveli pervane (172S: sabit hızlı), analog veya G1000 altı paket. Havayolu otomasyonu yok; her kontrol doğrudan hissedilir.', 3);

INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-001', 'Left Subpanel', 'Master Switch (BAT / ALT)', 'Ana Şalter (Batarya / Alternatör)', 'Sol alt panel', 'Batarya ve alternatörü açar/kapatır. Motor çalıştırmadan önce BAT ON olmalıdır.', 'Electrical', 0 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-002', 'Left Subpanel', 'Ignition / Magneto Key', 'Kontak / Magneto Anahtarı', 'Sol alt panel, anahtar', 'OFF-R-L-BOTH-START. Motor iki magnetodan kıvılcım alır; START konumunda starter çalışır.', 'Engine', 1 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-003', 'Left Subpanel', 'Fuel Selector Valve', 'Yakıt Seçici Vana', 'Zemin / koltuk arası, taban', 'BOTH / LEFT / RIGHT / OFF. Normal uçuşta BOTH. OFF yakıtı keser.', 'Fuel', 2 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-004', 'Throttle Quadrant', 'Throttle', 'Gaz Kolu', 'Panel altı, siyah kol', 'Motor gücünü ayarlar. İleri = tam gaz, geri = rölanti.', 'Engine Control', 3 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-005', 'Throttle Quadrant', 'Mixture Control', 'Karışım Kolu', 'Gazın sağında, kırmızı', 'Yakıt-hava karışımı. Zengin (ileri) kalkış/iniş, fakirleştirme irtifada. Tam geri = IDLE CUT-OFF, motor durur.', 'Engine Control', 4 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-006', 'Throttle Quadrant', 'Carburetor Heat', 'Karbüratör Isıtma', 'Gazın solunda', 'Karbüratör buzlanmasını giderir. Alçalış ve şüpheli buzlanmada ON.', 'Engine', 5 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-007', 'Throttle Quadrant', 'Flap Lever', 'Flap Kolu', 'Koltuğun arasında / sağ alt', '0-10-20-30 derece flap. Kalkış genelde 0 veya 10, iniş 20-30.', 'Flight Controls', 6 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-008', 'Center Pedestal', 'Elevator Trim Wheel', 'Yunuslama Trim Çarkı', 'Koltuk arası', 'Yoke kuvvetini nötrler. Burun yukarı/aşağı trim. Her güç ve flap değişiminde ayarlanır.', 'Flight Controls', 7 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-009', 'Yoke', 'Control Yoke', 'Kumanda Yoku', 'Pilot önü', 'Pitch (ileri-geri) ve roll (sağa-sola). Mekanik kablo.', 'Flight Controls', 8 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-010', 'Floor/Pedals', 'Rudder Pedals', 'Dümen Pedalları', 'Ayak altı', 'Yaw ve yerde burun tekeri yönlendirme; ayak uçları fren.', 'Flight Controls', 9 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-011', 'Main Instrument Panel', 'Airspeed Indicator', 'Hava Hızı Göstergesi (ASI)', 'Altı paket, üst sol', 'Knot cinsinden hava hızı. Beyaz yay flap, yeşil normal, sarı ihtiyat, kırmızı Vne.', 'Displays', 10 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-012', 'Main Instrument Panel', 'Attitude Indicator', 'Tutum Göstergesi (Yapay Ufuk)', 'Altı paket, üst orta', 'Uçağın ufka göre pitch ve bank açısı.', 'Displays', 11 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-013', 'Main Instrument Panel', 'Altimeter', 'Altimetre', 'Altı paket, üst sağ', 'İrtifa (feet). Kollinson QNH (Kollsman) penceresi ayarlanır.', 'Displays', 12 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-014', 'Main Instrument Panel', 'Turn Coordinator', 'Dönüş Koordinatörü', 'Altı paket, alt sol', 'Yatış oranı ve bilye (koordinasyon). Step on the ball.', 'Displays', 13 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-015', 'Main Instrument Panel', 'Heading Indicator', 'Yön Göstergesi (DI/HI)', 'Altı paket, alt orta', 'Manyetik pusulaya hizalanmış uçuş yönü. Periyodik olarak pusulaya set edilir.', 'Displays', 14 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-016', 'Main Instrument Panel', 'Vertical Speed Indicator', 'Dikey Hız Göstergesi (VSI)', 'Altı paket, alt sağ', 'Tırmanış/alçalış feet/dakika.', 'Displays', 15 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-017', 'Main Instrument Panel', 'Tachometer (RPM)', 'Devir Göstergesi', 'Sağ alt panel', 'Motor RPM. Yeşil yay sürekli güç, kırmızı çizgi limit.', 'Engine', 16 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-018', 'Main Instrument Panel', 'Fuel Quantity Gauges', 'Yakıt Miktar Göstergeleri', 'Sağ panel', 'Sol ve sağ kanat tankı yakıtı. Yere inmeden önce görsel kontrol şart.', 'Fuel', 17 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-019', 'Main Instrument Panel', 'Oil Pressure / Temperature', 'Yağ Basıncı / Sıcaklığı', 'Sağ panel', 'Motor yağ sağlığı. Düşük basınçta motor hemen kesilir.', 'Engine', 18 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-020', 'Switch Panel', 'Beacon / Nav / Strobe / Landing / Taxi Lights', 'Dış Işıklar', 'Sol alt şalter sırası', 'Beacon motor çalışırken, strobe uçuşta, landing iniş/kalkış.', 'Lighting', 19 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-021', 'Switch Panel', 'Pitot Heat', 'Pitot Isıtma', 'Sol şalterler', 'Hava hızı hortumunu buzdan korur. IMC ve görünür nemde ON.', 'Anti-Ice', 20 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-022', 'Radio Stack', 'COM / NAV Radios', 'Telsiz / NAV', 'Orta radyo yığını', 'Kule/yer frekansı ve VOR/ILS.', 'Communications', 21 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-023', 'Radio Stack', 'Transponder', 'Transponder', 'Radyo yığını altı', 'Squawk kodu. ALT mod radar irtifası gönderir. 7700 acil.', 'Surveillance', 22 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-024', 'Yoke / Floor', 'Parking Brake', 'Park Freni', 'Sol alt, yoke altı', 'Yerde uçağı tutar. Kalkış öncesi mutlaka bırakılır.', 'Brakes', 23 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-025', 'Left Subpanel', 'Primer', 'Yakıt Primörü', 'Sol alt, soğuk motorda', 'Soğuk çalışmada silindirlere yakıt püskürtür. Aşırı primer sel basmasına yol açar.', 'Engine', 24 FROM aircraft WHERE code = 'C172';
INSERT INTO cockpit_parts (aircraft_id, code, panel, name_en, name_tr, location, function_tr, category, sort_index) SELECT id, 'C172-026', 'Cabin', 'Cabin Heat / Air', 'Kabin Isıtma / Hava', 'Sağ alt', 'Egzoz ceketi ısısı ile kabin ısıtması. Karbonmonoksit riskine dikkat.', 'Environmental', 25 FROM aircraft WHERE code = 'C172';

